spring.application.name=spring-batch-demo-audit-it

app.messaging.customer-import.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

spring.datasource.url=jdbc:h2:mem:importAuditIt;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-h2-import-audit-it.sql

spring.batch.jdbc.initialize-schema=embedded
spring.batch.jdbc.platform=h2
spring.batch.job.enabled=false
