BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMER (
    ID NUMBER(19,0) PRIMARY KEY,
    NAME VARCHAR2(255),
    EMAIL VARCHAR2(255)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      NULL; -- already exists
    ELSE
      RAISE;
    END IF;
END;
/

