-- Oracle DDL: idempotent create (ignore ORA-955 table already exists).
-- spring.sql.init.separator is set in application-dev.properties. The delimiter line must NOT
-- start with "--" or Spring strips it as a comment, the separator is never seen, and init
-- falls back to newline splitting (breaking these PL/SQL blocks).

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE CUSTOMER (
    ID NUMBER(19,0) PRIMARY KEY,
    NAME VARCHAR2(255),
    EMAIL VARCHAR2(255)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      NULL; -- already exists
    ELSE
      RAISE;
    END IF;
END;

^^^ END ORACLE DDL ^^^

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE IMPORT_REJECTED_ROW (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
    CATEGORY VARCHAR2(32) NOT NULL,
    LINE_NUMBER NUMBER(19,0),
    REASON VARCHAR2(4000),
    SOURCE_ID VARCHAR2(64),
    SOURCE_NAME VARCHAR2(255),
    SOURCE_EMAIL VARCHAR2(255)
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      NULL; -- already exists
    ELSE
      RAISE;
    END IF;
END;

^^^ END ORACLE DDL ^^^

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE IMPORT_LAUNCH_CORRELATION (
    CORRELATION_ID VARCHAR2(64) PRIMARY KEY,
    JOB_EXECUTION_ID NUMBER(19,0) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
  )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      NULL; -- already exists
    ELSE
      RAISE;
    END IF;
END;
